# Generated by Django 5.1.7 on 2025-04-07 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='filial',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
