# Generated by Django 5.1.7 on 2025-04-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_remove_produto_filial_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco_unitario',
        ),
    ]
